# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anuncios.Categoria')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_homepage', to='home.HomePage')),
            ],
            options={
                'verbose_name': 'Categoría Pagina de Inicio',
                'verbose_name_plural': 'Categorías Pagina de Inicio',
            },
        ),
    ]
