# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('etiqueta', models.CharField(db_index=True, max_length=100)),
                ('icono', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria del Producto',
                'verbose_name_plural': 'Categorias de Productos',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('licencia', models.CharField(blank=True, db_index=True, help_text='Número de licencia con la que ejerce su actividad. Obligatoria solo para los trabajadores por cuenta propia que según el tipo de actividad que la requieran. Este datos no será público al resto de los usuarios.', max_length=100)),
                ('telefono', models.CharField(blank=True, db_index=True, max_length=12)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('nombre', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('titulo', models.CharField(db_index=True, help_text='El título debe ser directo y contener las palabras que mas definan los atributos de lo que usted quiere vender, comprar o intercambiar.', max_length=250)),
                ('contenido', models.TextField(help_text='Ofrezca los elementos necesarios para que su visitante pueda tomar una decisión')),
                ('foto', models.FileField(upload_to='productos/images/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('nombre', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('etiqueta', models.CharField(db_index=True, max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.Categoria')),
            ],
            options={
                'verbose_name': 'SubCategoria del Producto',
                'verbose_name_plural': 'SubCategorias de Productos',
            },
        ),
        migrations.CreateModel(
            name='TipoMoneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('moneda', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Precio del Producto',
                'verbose_name_plural': 'Precios de los Productos',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.SubCategoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.Contacto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.TipoMoneda'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.Provincia'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.Municipio'),
        ),
    ]
