# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_productpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomoneda',
            options={'verbose_name': 'Tipo de Moneda', 'verbose_name_plural': 'Tipos de Monedas'},
        ),
    ]
