# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_auto_20161215_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='contacto',
        ),
        migrations.AddField(
            model_name='producto',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='producto',
            name='licencia_contacto',
            field=models.CharField(blank=True, db_index=True, help_text='Número de licencia con la que ejerce su actividad. Obligatoria solo para los trabajadores por cuenta propia que según el tipo de actividad que la requieran. Este datos no será público al resto de los usuarios.', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='municipio_contacto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='anuncios.Municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_contacto',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='telefono_contacto',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
