# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_productlistpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='publicado',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='licencia_contacto',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
