# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0008_announcepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.FileField(blank=True, upload_to='media/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='publicado',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
